name: Sphinx Render docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step to set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify version explicitly

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip freeze  # Check if sphinx-design is installed

    # Explicitly install sphinx-design (if not installed in previous step)
    - name: Install sphinx-design explicitly
      run: pip install sphinx-design

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master  # Use a stable version of the action
      with:
        docs-folder: "docs/"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
