name: Build and Deploy Sphinx Documentation to GitHub Pages
# 
on:
  push:
    branches:
      - main  # Trigger on pushes to 'main'
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the OS if needed. Example: 'macos-latest', 'windows-latest'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # This action checks out your code. Usually, no change needed.

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Change '3.8' to the version of Python you want to use (e.g., '3.9', '3.10')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a 'requirements.txt' or install the required packages directly below

      - name: Install Sphinx and dependencies
        run: |
          pip install sphinx sphinx_rtd_theme  # If you are using other themes or extensions, install them here (e.g., 'sphinxcontrib-mermaid')

      - name: Build Sphinx documentation
        run: |
            sphinx-build -b html source build/html
        working-directory: ./docs  # Adjust this if needed

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4   # This action deploys the content to GitHub Pages
        with:
          branch: gh-pages  # Change 'gh-pages' to 'main' to deploy to the 'main' branch instead of 'gh-pages'
          folder: docs/build/html  # This should be the folder where Sphinx outputs the HTML files (usually '_build/html')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # No change needed here; this is automatically provided by GitHub Actions
          ACTIONS_STEP_DEBUG: true

