# # This is a basic workflow to help you get started with Actions
# # test2
# name: Build-sphinx-docs

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs: 
#   # This workflow contains a single job called "build"
#   build: 
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Set up Python 3.10
#         uses: actions/setup-python@v2
#         with:
#            python-version: "3.10"
#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!
        
#       - name: Install dependencies
#         run: | 
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Install ghp-import
#         run: |
#           python -m pip install ghp-import
#       - name: Build HTML
#         run: | 
#           cd docs/
#           make html
#       - name: Run ghp-import
#         run: | 
#           ghp-import -n -p -f docs/build/html

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

name: Build-sphinx-docs

on:
  push:
    branches: [ main ]  # Change to 'main' if that's your default branch
  pull_request:
    branches: [ main ]  # Change to 'main' if that's your default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build HTML
        run: |
          cd docs/
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses the default GitHub token for authentication
          publish_dir: docs/build/html  # Directory to deploy to GitHub Pages (change if necessary)
          publish_branch: main  # The branch to push to
          